{% set version = "2.3.3" %}

package:
  name: biobloomtools
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/bcgsc/biobloom/releases/download/{{ version }}/biobloomtools-{{ version }}.tar.gz
  sha256: cd3ca08677aae4cf99da30fdec87a23b12a8320c6d0e21df9d0c3b26b62b6153

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - boost
    - zlib
    - sparsehash
    - sdsl-lite
  run:
    - boost
    - zlib
    - sparsehash
    - sdsl-lite

about:
  home: https://github.com/bcgsc/biobloom
  license: GPL-3.0
  license_file: LICENSE
  summary: Tools for screening host species sequence using bloom filters.

